---
Name: twittercardmeta
After:
  - 'siteconfig/*'
Before:
  - 'mysite'
---
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - ToastNZ\TwitterCardMeta\Extensions\TwitterCardMeta

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - ToastNZ\TwitterCardMeta\Extensions\TwitterSiteConfigExtension
