---
Name: twittercardmeta
After:
  - 'siteconfig/*'
Before:
  - 'mysite'
---
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - TwitterCardMeta
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - TwitterSiteConfigExtension
